name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configurar Ícone da APK
        run: |
          # Cria os diretórios caso não existam
          mkdir -p app/src/main/res/mipmap-hdpi
          mkdir -p app/src/main/res/mipmap-mdpi
          mkdir -p app/src/main/res/mipmap-xhdpi
          mkdir -p app/src/main/res/mipmap-xxhdpi
          mkdir -p app/src/main/res/mipmap-xxxhdpi
    
          # Copia o ícone dos assets para as pastas de recursos (substitua 'seu_icone.png')
          cp assets/icone.png app/src/main/res/mipmap-hdpi/ic_launcher.png
          cp assets/icone.png app/src/main/res/mipmap-mdpi/ic_launcher.png
          cp assets/icone.png app/src/main/res/mipmap-xhdpi/ic_launcher.png
          cp assets/icone.png app/src/main/res/mipmap-xxhdpi/ic_launcher.png
          cp assets/icone.png app/src/main/res/mipmap-xxxhdpi/ic_launcher.png

      - name: Install Dependencies
        run: npm install

      - name: Build Web App
        run: |
          npm install @capacitor/cli @capacitor/core @capacitor/android
          npx vite build
          rm -rf android
          npx cap add android
          npx cap sync android
          
          # Remove os pacotes duplicados obsoletos do Kotlin que quebram o build
          echo "subprojects { configurations.all { exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'; exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8' } }" >> android/build.gradle

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk

